In [ ]:
from google.colab import drive
import numpy as np

import pydot
from matplotlib.pyplot import imshow
%matplotlib inline
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from PIL import Image
from imutils import paths
import os




drive.mount('/content/drive', force_remount=True)
#### Updated ####

#### Updated ####
### The following two lines caused the issue:
import sys
sys.path.append('/content/drive/My Drive')
### Replacing the above with these two lines solved the issue:
import os
os.chdir('/content/drive/My Drive') # Ch working directory to project folder
###

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
print("[INFO] loading images...")
imagePaths = paths.list_images('Dataset')
data = []
labels = []

[INFO] loading images...


In [ ]:
#setting path gambar di gdrive

print("[INFO] loading images...")
imagePathV = paths.list_images('CEK/Validasi')
imagePathD = paths.list_images('CEK/Dataset')

#imagePaths = paths.list_images('Dataset150')

data = []
labelsd = []
val = []
labelsv = []
aug = []
labels2 = []

[INFO] loading images...


In [ ]:
for imagePath in imagePaths:

  image = Image.open(imagePath).convert('L')

  image = np.array(image.resize((32,32))) / 255.0

  image = np.expand_dims(image, axis=-1)


  data.append(image)

  label = imagePath.split(os.path.sep) [-2]
  labelsd.append(label)

In [ ]:
#ambil dataset Asli tanpa augmen warna

for imagePath in imagePathV:

  a = Image.open(imagePath).convert('L')
  image = np.array(a.resize((32,32))) / 255.0
  image = np.expand_dims(image, axis=-1)

  val.append(image)

  label = imagePath.split(os.path.sep) [-2]
  labelsv.append(label)

In [ ]:
#Function buat Augmentasi
from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(
      rotation_range=105,
      width_shift_range=0.5,
      height_shift_range=0.5,
      shear_range=0.5,
      zoom_range=0.5,
      horizontal_flip=True,
      fill_mode='nearest')

In [ ]:
#masukin gambar warna dengan augmentasi dan asli 

for imagePath in imagePathD:

  a = Image.open(imagePath).convert('L')
  image = np.array(a.resize((32,32))) / 255.0
  image = np.expand_dims(image, axis=-1)

  x = image


  aug.append(x)
  x = x.reshape((1,) + x.shape)  # Numpy array with shape (1, 150, 150, 3)
  
  i = 0
  label = imagePath.split(os.path.sep) [-2]
  labels2.append(label)
  for batch in datagen.flow(x, batch_size=1):
    mas = x[0,:,:,:] #( 150, 150, 3)
    aug.append(mas)
    label = imagePath.split(os.path.sep) [-2]
    labels2.append(label)
    i += 1
    if i % 3 == 0:
      break 
  


In [ ]:
#membuat dan memasukkan gambar gray pake CLAHE dengan augmentasi dan asli
#note: pilih salah satu warna apa gray


import cv2

for imagePath in imagePathD:


  a = Image.open(imagePath)

  a = a.convert('L')


  image = np.array(a.resize((32,32))) 

  clahe = cv2.createCLAHE(clipLimit=4.0, tileGridSize=(8,8))

  image = clahe.apply(image)

  image = image / 255.0
  
  image = np.expand_dims(image, axis=-1)


  x = image


  aug.append(x)
  x = x.reshape((1,) + x.shape)  # Numpy array with shape (1, 150, 150, 3)
  
  i = 0
  label = imagePath.split(os.path.sep) [-2]
  labels2.append(label)
  for batch in datagen.flow(x, batch_size=1):
    mas = x[0,:,:,:] #( 150, 150, 3)
    aug.append(mas)
    label = imagePath.split(os.path.sep) [-2]
    labels2.append(label)
    i += 1
    if i % 3 == 0:
      break 
  


In [ ]:
#masukin gambar warna dengan augmentasi dan asli 

for imagePath in imagePaths:

  a = Image.open(imagePath).convert('L')
  image = np.array(a.resize((32,32))) / 255.0
  image = np.expand_dims(image, axis=-1)

  x = image
  data.append(x)
  label = imagePath.split(os.path.sep) [-2]
  labels.append(label)

  aug.append(x)
  x = x.reshape((1,) + x.shape)  # Numpy array with shape (1, 150, 150, 3)
  
  i = 0
  label = imagePath.split(os.path.sep) [-2]
  labels2.append(label)
  for batch in datagen.flow(x, batch_size=1):
    mas = x[0,:,:,:] #( 150, 150, 3)
    aug.append(mas)
    label = imagePath.split(os.path.sep) [-2]
    labels2.append(label)
    i += 1
    if i % 3 == 0:
      break 
  


In [ ]:
print(labels)
lb = LabelBinarizer()
labels = lb.fit_transform(labels)
print(labels)

['Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA ', 'Grade AA '

In [ ]:
#ini one hot encoding dataset tanpa augmentasi, 
print(labelsv)
lb = LabelBinarizer()
labelsv = lb.fit_transform(labelsv)
print(labelsv)

['Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade AA', 'Grade A', 'Grade A', 'Grade A', 'Grade A', 'Grade A', 'Grade A', 'Grade A', 'Grade A', 'Grade A', 'Grade A', 'Grade A', 'Grade A', 'Grade A', 'Grade A', 'Grade A', 'Grade A', 'Grade A', 'Grade A', 'Grade A', 'Grade A', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade B', 'Grade C', 'Grade C', 'Grade C', 'Grade C', 'Grade C', 'Grade C', 'Grade C', 'Grade C', 'Grade C', 'Grade C']
[[0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]

In [ ]:
#ini one hot encoding dataset tanpa augmentasi, 
print(labels2)
lb = LabelBinarizer()
labels2 = lb.fit_transform(labels2)
print(labels2)

[[0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 ...
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]]
[[0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 ...
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]]


In [ ]:
(trainX,testX, trainY, testY) = train_test_split(np.array(data),np.array(labels), test_size=0.20)
print(trainX.shape)
print(testX.shape)
trainY.shape
print(trainY)

(758, 32, 32, 1)
(190, 32, 32, 1)
[[0 1 0 0]
 [1 0 0 0]
 [0 1 0 0]
 ...
 [0 1 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [ ]:
#ini set data Train kalau pake augmen

(trainX,dumbx, trainY, dumby) = train_test_split(np.array(aug),
np.array(labels2),test_size=0.05)
print(trainX.shape)
print(trainY.shape)


(3328, 32, 32, 1)
(3328, 4)


In [ ]:
#ini set data Test kalau pake augmen
#ini dan cell atas harus di run

(dumbx,testX, dumby, testY) = train_test_split(np.array(val),
np.array(labelsv), test_size=70)
print(testX.shape)
print(testY.shape)

(70, 32, 32, 1)
(70, 4)


In [ ]:
from keras.models import Sequential
from keras import models, layers
from keras.optimizers import Adam, SGD


import keras
#Instantiate an empty model
model = Sequential()

# C1 Convolutional Layer
model.add(layers.Conv2D(6, kernel_size=(5, 5), strides=(1, 1), activation='tanh', input_shape=(32,32,1), padding="same"))

# S2 Pooling Layer
model.add(layers.AveragePooling2D(pool_size=(2, 2), strides=(1, 1), padding='valid'))

# C3 Convolutional Layer8
model.add(layers.Conv2D(16, kernel_size=(5, 5), strides=(1, 1), activation='tanh', padding='valid'))

# S4 Pooling Layer
model.add(layers.AveragePooling2D(pool_size=(2, 2), strides=(2, 2), padding='valid'))

# C5 Fully Connected Convolutional Layer
model.add(layers.Conv2D(120, kernel_size=(5, 5), strides=(1, 1), activation='tanh', padding='valid'))
#Flatten the CNN output so that we can connect it with fully connected layers
model.add(layers.Flatten())

# FC6 Fully Connected Layer
model.add(layers.Dense(84, activation='tanh'))

#Output Layer with softmax activation
model.add(layers.Dense(4, activation='softmax'))

# Compile the model
opt = SGD(lr = 1e-3)
model.compile(loss=keras.losses.categorical_crossentropy, optimizer=opt, metrics=["accuracy"])

In [ ]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_7 (Conv2D)            (None, 32, 32, 6)         156       
_________________________________________________________________
average_pooling2d_5 (Average (None, 31, 31, 6)         0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 27, 27, 16)        2416      
_________________________________________________________________
average_pooling2d_6 (Average (None, 13, 13, 16)        0         
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 9, 9, 120)         48120     
_________________________________________________________________
flatten_3 (Flatten)          (None, 9720)              0         
_________________________________________________________________
dense_5 (Dense)              (None, 84)               

In [ ]:
H = model.fit(x=trainX,y=trainY, epochs=50, batch_size=32, validation_data=(testX, testY), verbose=1)
predY=model.predict(testX)


Train on 3328 samples, validate on 70 samples
Epoch 1/50
3328/3328 [==============================] - 1s 163us/step - loss: 1.3359 - accuracy: 0.3305 - val_loss: 1.3505 - val_accuracy: 0.3000
Epoch 2/50
3328/3328 [==============================] - 0s 126us/step - loss: 1.3296 - accuracy: 0.3299 - val_loss: 1.3477 - val_accuracy: 0.3286
Epoch 3/50
3328/3328 [==============================] - 0s 129us/step - loss: 1.3295 - accuracy: 0.3284 - val_loss: 1.3473 - val_accuracy: 0.3000
Epoch 4/50
3328/3328 [==============================] - 0s 125us/step - loss: 1.3268 - accuracy: 0.3302 - val_loss: 1.3502 - val_accuracy: 0.3000
Epoch 5/50
3328/3328 [==============================] - 0s 115us/step - loss: 1.3257 - accuracy: 0.3263 - val_loss: 1.3453 - val_accuracy: 0.3000
Epoch 6/50
3328/3328 [==============================] - 0s 116us/step - loss: 1.3240 - accuracy: 0.3329 - val_loss: 1.3498 - val_accuracy: 0.3000
Epoch 7/50
3328/3328 [==============================] - 0s 118us/step - loss: 

In [ ]:
H = model.fit(x=trainX,y=trainY, epochs=50, batch_size=32, validation_data=(testX, testY), verbose=1)
predY=model.predict(testX)


Train on 758 samples, validate on 190 samples
Epoch 1/50
758/758 [==============================] - 0s 322us/step - loss: 1.3239 - accuracy: 0.3430 - val_loss: 1.2922 - val_accuracy: 0.4053
Epoch 2/50
758/758 [==============================] - 0s 306us/step - loss: 1.3237 - accuracy: 0.3549 - val_loss: 1.2908 - val_accuracy: 0.3789
Epoch 3/50
758/758 [==============================] - 0s 297us/step - loss: 1.3227 - accuracy: 0.3536 - val_loss: 1.2946 - val_accuracy: 0.3842
Epoch 4/50
758/758 [==============================] - 0s 306us/step - loss: 1.3241 - accuracy: 0.3509 - val_loss: 1.2927 - val_accuracy: 0.3895
Epoch 5/50
758/758 [==============================] - 0s 305us/step - loss: 1.3230 - accuracy: 0.3628 - val_loss: 1.2882 - val_accuracy: 0.3842
Epoch 6/50
758/758 [==============================] - 0s 314us/step - loss: 1.3220 - accuracy: 0.3654 - val_loss: 1.2887 - val_accuracy: 0.3842
Epoch 7/50
758/758 [==============================] - 0s 305us/step - loss: 1.3215 - accur

In [ ]:
#evaluasi
print("[INFO] evaluating network...")
predictions = model.predict(testX, batch_size=32)
print(classification_report(testY.argmax(axis=1), predictions.argmax(axis=1), target_names=lb.classes_))

[INFO] evaluating network...


NameError: ignored

In [ ]:
#evaluasi
print("[INFO] evaluating network...")
predictions = model.predict(testX, batch_size=32)
print(classification_report(testY.argmax(axis=1), predictions.argmax(axis=1), target_names=lb.classes_))

[INFO] evaluating network...
              precision    recall  f1-score   support

     Grade A       0.28      0.11      0.16        46
   Grade AA        0.40      0.35      0.37        48
     Grade B       0.41      0.68      0.51        78
    Grade C        0.00      0.00      0.00        18

    accuracy                           0.39       190
   macro avg       0.27      0.29      0.26       190
weighted avg       0.34      0.39      0.34       190



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#evaluasi 2
test_score = model.evaluate(testX, testY, batch_size = 32)
print("Test loss {:.4f}, accuracy {:.2f}%".format(test_score[0], test_score[1] * 100))

190/190 [==============================] - 0s 177us/step
Test loss 1.2871, accuracy 38.95%


In [ ]:
#bikin grafik epoch sama Val_acc
from matplotlib import pyplot as plt
import pandas as pd

epochs = H.epoch
hist = pd.DataFrame(H.history)
list_of_metrics_to_plot = ['val_acc']
plot_curve(epochs, hist, list_of_metrics_to_plot)


In [ ]:
#grafik val_acc sama train_acc
import matplotlib.pyplot as plt
f, ax = plt.subplots()
ax.plot([None] + H.history['acc'], 'o-')
ax.plot([None] + H.history['val_acc'], 'x-')
# Plot legend and use the best location automatically: loc = 0.
ax.legend(['Train acc', 'Validation acc'], loc = 0)
ax.set_title('Training/Validation acc per Epoch')
ax.set_xlabel('Epoch')
ax.set_ylabel('acc')

In [ ]:
#grafik loss train dengan loss val
import matplotlib.pyplot as plt
f, ax = plt.subplots()
ax.plot([None] + H.history['loss'], 'o-')
ax.plot([None] + H.history['val_loss'], 'x-')
# Plot legend and use the best location automatically: loc = 0.
ax.legend(['Train Loss', 'Validation Loss'], loc = 0)
ax.set_title('Training/Validation Loss per Epoch')
ax.set_xlabel('Epoch')
ax.set_ylabel('Loss')

In [ ]:
#Bikin Confusion
from sklearn.metrics import confusion_matrix

labels=["Grade AA", "Grade A", "Grade B","Grade C"]
print(confusion_matrix(testY, predY))


In [ ]:
#run 
from sklearn.metrics import multilabel_confusion_matrix
cm=multilabel_confusion_matrix(testY,predY)
print(cm)


In [ ]:
#run
from sklearn.metrics import multilabel_confusion_matrix

predY[1]
rounded_labels=np.argmax(predY, axis=1)
rounded_labels[1]
rounded_predict=np.argmax(testY, axis=1)
rounded_predict[1]
print(confusion_matrix(rounded_labels, rounded_predict))
rounded_labels[:,2]


In [ ]:
import numpy as np


def plot_confusion_matrix(cm,
                          target_names=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11'],
                          title='Confusion matrix',
                          cmap=None,
                          normalize=True):
    """
    given a sklearn confusion matrix (cm), make a nice plot

    Arguments
    ---------
    cm:           confusion matrix from sklearn.metrics.confusion_matrix

    target_names: given classification classes such as [0, 1, 2]
                  the class names, for example: ['high', 'medium', 'low']

    title:        the text to display at the top of the matrix

    cmap:         the gradient of the values displayed from matplotlib.pyplot.cm
                  see http://matplotlib.org/examples/color/colormaps_reference.html
                  plt.get_cmap('jet') or plt.cm.Blues

    normalize:    If False, plot the raw numbers
                  If True, plot the proportions

    Usage
    -----
    plot_confusion_matrix(cm           = cm,                  # confusion matrix created by
                                                              # sklearn.metrics.confusion_matrix
                          normalize    = True,                # show proportions
                          target_names = y_labels_vals,       # list of names of the classes
                          title        = best_estimator_name) # title of graph

    Citiation
    ---------
    http://scikit-learn.org/stable/auto_examples/model_selection/plot_confusion_matrix.html

    """
    import matplotlib.pyplot as plt
    import numpy as np
    import itertools

    accuracy = np.trace(cm) / float(np.sum(cm))
    misclass = 1 - accuracy

    if cmap is None:
        cmap = plt.get_cmap('Blues')

    plt.figure(figsize=(8, 6))
    if normalize:
      plt.imshow(cm/7, interpolation='nearest', cmap=cmap)
    else:
      plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()

    if target_names is not None:
        tick_marks = np.arange(len(target_names))
        plt.xticks(tick_marks, target_names, rotation=45)
        plt.yticks(tick_marks, target_names)

    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]


    thresh = cm.max() / 1.5 if normalize else cm.max() / 2
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        if normalize:
            plt.text(j, i, "{:0.3f}".format(cm[i, j]),
                     horizontalalignment="center",
                     color="white" if cm[i, j] > thresh else "black")
        else:
            plt.text(j, i, "{:,}".format(cm[i, j]),
                     horizontalalignment="center",
                     color="white" if cm[i, j] > thresh else "black")


    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label\naccuracy={:0.4f}; misclass={:0.4f}'.format(accuracy, misclass))
    plt.show()

In [ ]:
#run
#gambar confusion matrix
cm = confusion_matrix(rounded_labels,  rounded_predict)
plot_confusion_matrix(cm)

In [ ]:
import numpy as np
import random
import matplotlib.pyplot as plt

from tensorflow.keras.preprocessing.image import img_to_array, load_img

# Let's define a new Model that will take an image as input, and will output
# intermediate representations for all layers in the previous model after
# the first.
#inputs = Input(shape=(224, 224, 3))
successive_outputs = [layer.output for layer in model.layers[1:]]
visualization_model = Model(inputs, successive_outputs, name = "Lenet")

img = load_img('Dataset/Grade A/IMG_0507.jpg', target_size=(32, 32))

x = img_to_array(img)  # Numpy array with shape (150, 150, 3)
x = x.reshape((1,) + x.shape)  # Numpy array with shape (1, 150, 150, 3)

# Rescale by 1/255
x /= 255

# Let's run our image through our network, thus obtaining all
# intermediate representations for this image.
successive_feature_maps = visualization_model.predict(x)

# These are the names of the layers, so can have them as part of our plot
layer_names = [layer.name for layer in model.layers]

# Now let's display our representations
for layer_name, feature_map in zip(layer_names, successive_feature_maps):
  if len(feature_map.shape) == 4:
    # Just do this for the conv / maxpool layers, not the fully-connected layers
    n_features = feature_map.shape[-1]  # number of features in feature map
    # The feature map has shape (1, size, size, n_features)
    size = feature_map.shape[1]
    # We will tile our images in this matrix
    display_grid = np.zeros((size, size * n_features))
    for i in range(n_features):
      # Postprocess the feature to make it visually palatable
      x = feature_map[0, :, :, i]
      x -= x.mean()
      x /= x.std()
      x *= 64
      x += 128
      x = np.clip(x, 0, 255).astype('uint8')
      # We'll tile each filter into this big horizontal grid
      display_grid[:, i * size : (i + 1) * size] = x
    # Display the grid
    scale = 20. / n_features
    plt.figure(figsize=(scale * n_features, scale))
    plt.title(layer_name)
    plt.grid(False)
    plt.imshow(display_grid, aspect='auto', cmap='viridis')